### ISSUE TITLE
Missing date

### ISSUE THREAD

**Issue by Rafnuss** [Rafnuss/GeoPressureAPI#11]
Basic example not working:
```
http://glp.mgravey.com:24853/GeoPressure/v1/timeseries/?lon=-79.9&lat=32.7&time=[1651727319,1651729119,1651730919,1651732719,1651734519,1651736319,1651738119,1651739919,1651741719]&pressure=[101378.272,101331.727,101312.729,101300.572,101280.063,101280.684,101240.285,101228.934,101211.172]
```

The return csv has only 4 rows:

time | pressure | altitude
-- | -- | --
1651730919 | 101482.809 | 19.7660724
1651732719 | 101482.809 | 20.8027174
1651734519 | 101482.809 | 22.551778
1651736319 | 101482.809 | 22.4988133

@mgravey any idea?

</body>

</html>

**Comment by Rafnuss** [comment]
Nope. Any idea or the origin ? Can you reproduce it ?

**Comment by mgravey** [comment]
this could be due to the closest-point strategy when requesting a point out of the ERA5 grid. I don't know if we could do anything about this
