### ISSUE TITLE
Error `Parameter 'image' is required.`

### ISSUE THREAD

**Issue by Rafnuss** [Rafnuss/GeoPressureAPI#12]
**task_id**:1662483417

`error1662483417Image.mask: Parameter 'image' is required.An error has occurred.`

**Comment by Rafnuss** [comment]
Error due to request with date too recent.

**Comment by Rafnuss** [comment]
fixed in GeoPressureR with https://github.com/Rafnuss/GeoPressureR/pull/39/commits/28d236a261928204e293af96f1ce39eb465b24cc.

**Comment by mgravey** [comment]
fixed on server side in  8e72cf2d65b4ea233ea18dd71920cf53e7174c95
