### ISSUE TITLE
Single value with pressure return a map of zeros instead of 1

### ISSUE THREAD

**Issue by Rafnuss** [Rafnuss/GeoPressureAPI#13]
If you only have a single value of pressure, I'm expecting the probability map returned to be full of 1 (all positions are possible) rather than 0.

Example:

```
http://glp.mgravey.com:24853/GeoPressure/v1/map/?W=-18&S=4&E=16&N=51&time=[1572075000]&pressure=[97766]&label=[1]
```
Left map should be 1 everywhere in my opinion:

![image](https://user-images.githubusercontent.com/7571260/192165630-21f30c68-38b7-43c0-8822-9418b10f6dc8.png)

**Comment by mgravey** [comment]
I see any bug,
1st variable 0 errors, so it returns 0 everywhere.
2nd variable return 1 in possible location, and 0 in the non-possible ones.
