### ISSUE TITLE
Service Status

### ISSUE THREAD

**Issue by Anathemch** [Rafnuss/GeoPressureAPI#8]
Hi together

Is it possible to implement an API to check, if your service is available?
At the moment I can't get information from glp.mgravey.com:24853.

I tried it with your example: 
glp.mgravey.com:24853/GeoPressure/v1/map/?W=-18&S=4&E=16&N=51&time=[1572075000,1572076800,1572078600]&pressure=[97766,97800,97833]&label=[1,1,1]

Thank you and regards
Roger

**Comment by mgravey** [comment]
Hi Roger,
What do you mean with an API check ? Like a URL to check if it's working or not ?
This will require an extra server that i don't have, so I would say NO :)
However, we have once the day a check if the server answer using GitHub Action. You can see the status on the main page. The small flag (green or red) on the top in the readme.

I just deployed a new version that should be less prone to crashes, let see.
@Rafnuss will probably soon publish and updated R package to take care of this. (It required some  minor modifications in R, to handle lots of data, like long-time series.)

Best,
Mathieu

**Comment by Rafnuss** [comment]
Hi @Anathemch,
Is this still an issue? Is it possible to access the API from Sempach now ?
